### ISSUE TITLE
Positional arguments missing error

### ISSUE THREAD

**Issue by pand6400** [sunlightlabs/validictory#82]
I am trying to use validictory package in python 2.6 and the validator failed due to the following error.

 File "build/bdist.linux-x86_64/egg/validictory/validator.py", line 275, in validate_items
    '{}[{}]'.format(path, index))
ValueError: zero length field name in format

Suggestions online:
In Python 2.6, you need indices in the format specs, like this:
"{0} {1}\n".format(x,y)

**Comment by jamesturk** [comment]
sorry, Python 2.6 is not supported by the latest versions of Validictory.  Python 2.6 hit its end of life over a year ago (October 2013)

**Comment by pand6400** [comment]
Ok Thank you.
