### ISSUE TITLE
patternProperties failing

### ISSUE THREAD

**Issue by mexicarne** [sunlightlabs/validictory#87]
Hello. 

I'm using this code from validictory tests:

```python
import validictory
schema = { "patternProperties": {"[abc]": {"type": "boolean"}}}
data = { "a":True, "d":"foo"}
validictory.validate(data, schema)
```
If I understand correctly, it should not validate this because **d** is not in **[abc]** and value type of **d** is string, not boolean. Homewer, it validates fine. I'm using validictory 1.0.0 from PyPi

**Comment by jamesturk** [comment]
I think you want additionalProperties: false - look here for an example
http://json-schema.org/example2.html

On Tue, Apr 28, 2015 at 7:20 AM, Ruslan <notifications@github.com> wrote:

> Hello.
>
> I'm using this code from validictory tests:
>
> import validictory
> schema = { "patternProperties": {"[abc]": {"type": "boolean"}}}
> data = { "a":True, "d":"foo"}
> validictory.validate(data, schema)
>
> If I understand correctly, it should not validate this because *d* is not
> in *[abc]* and value type of *d* is string, not boolean. Homewer, it
> validates fine. I'm using validictory 1.0.0 from PyPi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/validictory/issues/87>.
>



-- 

James Turk
Labs Director | Sunlight Foundation <http://www.sunlightfoundation.com/>
202-558-8723 | @JamesTurk <https://twitter.com/jamesturk>

[image: Sunlight Foundation] <http://sunlightfoundation.com/>

**Comment by mexicarne** [comment]
Oh, looks like it works with test code, so I'll try with my real code. Thank you and sorry for false alarm.

**Comment by jamesturk** [comment]
No problem, thanks!
